### ISSUE TITLE
Rendering of links from node to self

### ISSUE THREAD

**Issue by jamesscottbrown** [networkcube/vistorian-nodelink#26]
@alkadi-mh reports that these are not rendered well:

<img width="634" alt="self-link" src="https://user-images.githubusercontent.com/338833/127019520-ba08a06d-2dff-426d-aaac-35c48ce21b05.png">

We should probably check if the source and target nodes are the same [here](https://github.com/networkcube/vistorian-nodelink/blob/master/src/nodelink.ts#L374) and [here](https://github.com/networkcube/vistorian-nodelink/blob/master/src/nodelink.ts#L423), and if they are then set the `path`'s `d` element to be a curved arc rather than a straight line.

N.B. - if there are multiple self-links to/from the same node, these can be distinguished by giving each a different radius of curvature.

**Comment by benjbach** [comment]
Fixed.
